export {
    hasDocument,
    hasWindow,
    documentHeight,
    windowWidth,
    windowHeight,
    scrollTopDistance,
    scrollLeftDistance,
    height,
    rawHeight,
    rawHeightWithMargin,
    width,
    rawWidth,
    rawWidthWithMargin,
    topEdgeDistance,
    bottomEdgeDistance,
    leftEdgeDistance,
    rightEdgeDistance,
    inViewport
} from './measure';